### ISSUE TITLE
Create Skeletal PPP for v1.1

### ISSUE THREAD

**Issue by kevinchangjk** [AY2223S1-CS2103T-T15-1/tp#12]
Each team member is to start on their PPP by creating a basic skeleton for `v1.1`.

The subtasks (for individual members) are as below:
- Chao Yung #11
- Kevin #9 
- Prittam #5 
- Shawn #7 
- Shi Jun #6

**Comment by kevinchangjk** [comment]
All done very nice. 💯

**Comment by Kok-je** [comment]
LGTM
