### ISSUE TITLE
[PE-D][Tester D] Additional space in quickstart command

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T15-1/tp#163]
![image.png](https://raw.githubusercontent.com/TheSoggy/ped/main/files/27295a53-c492-4165-9e47-67b3faf71a3f.png)
There is an additional space here as compared to 
![image.png](https://raw.githubusercontent.com/TheSoggy/ped/main/files/5d675a12-789b-4dfc-b5eb-12981c72eab4.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: TheSoggy/ped#2

**Comment by kevinchangjk** [comment]
Accepted, will fix with #157.

**Comment by kevinchangjk** [comment]
Fixed with #221.
