### ISSUE TITLE
[PE-D][Tester D] Optional fields not wrapped in square brackets

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T15-1/tp#171]
![image.png](https://raw.githubusercontent.com/TheSoggy/ped/main/files/91911c1f-6a99-4297-b976-af39916c4a21.png)
Why not `add n/NAME j/POSITION d/DEPARTMENT [p/PHONE] [e/EMAIL] [a/ADDRESS] [l/LEAVE] [t/TAG]…​` if in the command format the square bracket has been defined as an optional field?

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: TheSoggy/ped#5

**Comment by kevinchangjk** [comment]
Accepted, will fix with #157.

**Comment by kevinchangjk** [comment]
Fixed in #157.
