### ISSUE TITLE
[PE-D][Tester A] JAR File: When adding a person to Coydir, we can specify nonsense values for Position field and it works

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T15-1/tp#177]
## Reproducing the Bug

1. Open the `.jar` file using the `java -jar` command.

1. Run the command `add n/TestUser j/123 d/Human Resources`.

1. Notice that the user has been added with a nonsense position of `123`.

![Screenshot 2022-10-28 at 4.33.50 PM.png](https://raw.githubusercontent.com/DanielLimWeiEn/ped/main/files/f971031d-38b6-45df-9a35-52f7a94fad3f.png)

## Expected Behaviour

The application should do some validation of possible positions or perhaps only allow String values to be in the position field.

## Actual Behaviour

The application allows nonsense values such as numbers (123) when entering the command.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: DanielLimWeiEn/ped#2

**Comment by kevinchangjk** [comment]
I think this one isn't a bug.

It's difficult to "validate" positions, when there is no real, legal, restriction on what a position is in the first place. 

When I was implementing the `Position` class, I thought that there might be users who would like to include numbers in the position for their employees, for level-setting, as part of the actual job title, or maybe as additional differentiating factors.

What do you all think? A simple fix would be to just change the regex to string alone.

**Comment by prit3010** [comment]
I agree too because we cannot allow for only String values as there are positions unqiue to the company like Software Engineer Level 3.

**Comment by prit3010** [comment]
I shall close this issue.
