### ISSUE TITLE
[PE-D][Tester E] Possible integer overflow of Employee ID

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T15-1/tp#179]
Since the employee IDs keep increasing and deleted employee IDs are not utilised, it might be possible to hit an integer overflow, albeit it is very unlikely since I do not expect to have even 2^31 employees.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: kangzongxian/ped#8

**Comment by kevinchangjk** [comment]
Valid point, though I'm not sure if this is something we want to focus on.

**Comment by kevinchangjk** [comment]
What do you all think? Else we can close this as a "won't fix".

**Comment by prit3010** [comment]
Think this should be a no fix as it is stated in the User Guide we are unable to hangle Big Int

**Comment by kevinchangjk** [comment]
This one isn't so much about user input, as it is about employee ID being over the max integer limit. Realistically, that won't happen, so I find it hard to justify a user needing such a requirement, but it's not difficult to implement also.

**Comment by kevinchangjk** [comment]
Never mind, won't fix.
