### ISSUE TITLE
[PE-D][Tester E] Not too sure who is on leave when using 'viewdepartment' command.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T15-1/tp#181]
When using viewdepartment, it displays the total number of employees, available employees, and the number of employees on leave. It would be useful if I could see which employee is on leave as well, rather than having to find them individually.

![Screenshot 2022-10-28 at 4.40.14 PM.png](https://raw.githubusercontent.com/kangzongxian/ped/main/files/b9dd6dbe-fcf6-4582-aae1-16627375d582.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: kangzongxian/ped#9

**Comment by prit3010** [comment]
Good Suggestion. Unfortunately, we are unable to fix this due to the feature freeze.
