### ISSUE TITLE
[PE-D][Tester C] Full address not shown

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T15-1/tp#187]
![image.png](https://raw.githubusercontent.com/TanPingZhi/ped/main/files/8513449b-3576-4104-b53a-fc728700cf9b.png)

## Problem:
The app is unable to show long addresses in the list

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: TanPingZhi/ped#3

**Comment by kevinchangjk** [comment]
Is this something worth taking a look into?

**Comment by kevinchangjk** [comment]
Duplicate with #203.
