### ISSUE TITLE
[PE-D][Tester E] Lacking images of how to use batchadd command in User Guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T15-1/tp#190]
As the batchadd command is rather complex that require fields to be entered properly based on the specifications, it would be tremendously useful to have supporting images so that the reader can better understand.

Screenshot:

![Screenshot 2022-10-28 at 4.47.10 PM.png](https://raw.githubusercontent.com/kangzongxian/ped/main/files/82cabf32-5a35-4e5c-963b-fd182b58fea9.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: kangzongxian/ped#14

**Comment by kevinchangjk** [comment]
Accepted, will fix with #157.

**Comment by kevinchangjk** [comment]
Also duplicate with aforementioned, #193. Best to add more detail on the format in words with accompanying visuals.
