### ISSUE TITLE
[PE-D][Tester E] In User Guide, the command summary does not specify the optional fields appropriately.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T15-1/tp#194]
In the User Guide, the add and edit commands for example did not specify the fields that can be optional with '[ ]'.

Screenshot:

![Screenshot 2022-10-28 at 4.49.56 PM.png](https://raw.githubusercontent.com/kangzongxian/ped/main/files/f889fe57-5053-4cc1-9de3-86ae1191730f.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: kangzongxian/ped#16

**Comment by kevinchangjk** [comment]
Accepted, will fix with #157.
