### ISSUE TITLE
[PE-D][Tester E] Able to enter more than 15 digits for phone numbers

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T15-1/tp#202]
According to the international phone numbering plan, phone numbers cannot contain more than 15 digits. It would be good to guard against that as well.

Screenshot:
![Screenshot 2022-10-28 at 4.59.53 PM.png](https://raw.githubusercontent.com/kangzongxian/ped/main/files/c58b7a98-2f7c-44f8-b751-7f722b84bab3.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: kangzongxian/ped#19

**Comment by prit3010** [comment]
I can do this
