### ISSUE TITLE
[PE-D][Tester D] Rating multiple times in a day results in a straight line graph

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T15-1/tp#210]
![image.png](https://raw.githubusercontent.com/TheSoggy/ped/main/files/7cb1eb1d-b3d4-4b16-b674-dc7d7385a9e5.png)
Perhaps a user should be prevented to rate multiple times in a day?

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: TheSoggy/ped#15

**Comment by kevinchangjk** [comment]
@Kok-je what do you think?

**Comment by Kok-je** [comment]
@kevinchangjk Hmm perhaps we can fix with a checker that sees if performance field is not "N/A", then users will be thrown an "employee rating completed" error?

**Comment by kevinchangjk** [comment]
Yeah I think can. So that means users are not meant to rate multiple times a day?

**Comment by Kok-je** [comment]
Yea ig to fix the straight line graph error.
