### ISSUE TITLE
[PE-D][Tester C] Employee id does not restart after clearing database

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T15-1/tp#217]
![image.png](https://raw.githubusercontent.com/TanPingZhi/ped/main/files/dc1dd8f1-43e7-4209-ab8c-395fa6b9ac63.png)

## Problem:
If im a new user, I will miscount the number of employees i have

## How to replicate:
1. Clear command
2. Add new employee

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: TanPingZhi/ped#7

**Comment by kevinchangjk** [comment]
Accepted, clear should restart the database, which is a mismatch of the actual behaviour.

**Comment by kevinchangjk** [comment]
Fixed with #230.
