### ISSUE TITLE
Request: Ability for the CLI to detect correct command and change color accordingly

### ISSUE THREAD

**Issue by ngshijun** [AY2223S1-CS2103T-T15-1/tp#68]
Request to add an extra feature: color of the command changes based on whether it is a valid command

### Example of valid command
<img width="974" alt="image" src="https://user-images.githubusercontent.com/37807290/194168539-87581d94-6e3a-4dc1-a590-a1e436aa3097.png">

### Example of invalid command
<img width="974" alt="image" src="https://user-images.githubusercontent.com/37807290/194168586-91f5532c-38cf-4f54-b63f-54a83e32df39.png">

**Comment by kevinchangjk** [comment]
Will close this now as we won't be fixing this at all.
