### ISSUE TITLE
Update Developer Guide

### ISSUE THREAD

**Issue by chao890** [AY2223S1-CS2103T-T15-1/tp#86]
The guidelines to each feature in the developer guide are: Description of implementation, Rationale of implementation, with code snippets and UML diagrams to aid your explanations.

These are the features that need to be added:
1. Add Command (already implemented) #95
2. BatchAdd Command (already implemented) #96 
3. View Command (already implemented) #100 
4. Delete Command (already implemented) #102 
6. Find Command **(not yet implemented)** #98 

Note: Current updates are not final, more changes will be made as we develop more features

**Comment by kevinchangjk** [comment]
Remember to remove instances of "Address Book" in the Developer Guide as well.
