### ISSUE TITLE
Improve functionality of Find Function

### ISSUE THREAD

**Issue by prit3010** [AY2223S1-CS2103T-T15-1/tp#89]
As a user, I can filter people based on department, so that I can keep track of who is in what department.
As a user, I can filter people based on job position, so that I can get the number of people in that specific role.

As of now, Coydir has a Find function that can find an employee of a certain name. 

Improve the Find function so that Coydir can find by department and job position. 
Find function can have up to 3 arguments - Name Department and Position. If multiple arguments are inputed, all must match to output it out.

**Comment by kevinchangjk** [comment]
Note that this means we will need to implement the Department field of the `Person` class as well. This field will have to:

- Be in the `Person` class
- Be available to set in `add` and `edit` commands
- Be restricted to a list of customised valid departments for the company
- Be customisable in some way (can add, remove, edit)
