### ISSUE TITLE
Bug found

### ISSUE THREAD

**Issue by prit3010** [AY2223S1-CS2103T-T15-1/tp#93]
While I was playing around with Coydir, I suddenly ran into this error.

<img width="740" alt="Screenshot 2022-10-17 at 11 45 24 PM" src="https://user-images.githubusercontent.com/64403191/196223053-e2d12dd0-a6b4-462d-8ebb-d28a8b82d4b5.png"> 

Error is as such:
<img width="1061" alt="Screenshot 2022-10-17 at 11 47 51 PM" src="https://user-images.githubusercontent.com/64403191/196223466-cdb1dace-5c29-49c1-b36e-f8f7c7e6af16.png">

Upon backtracking, I found where this issue comes from. Once I add a input with no fields other than name and position, I get the error when I try start it up

<img width="739" alt="Screenshot 2022-10-17 at 11 49 44 PM" src="https://user-images.githubusercontent.com/64403191/196223925-120a1dcb-4efb-44d7-8f97-ecf817ff44a8.png">

Seems to be an issue with the parsing of the N/A fields from the `database.json`

Please advise

**Comment by kevinchangjk** [comment]
Hmm, that kinda makes sense actually.

I think we can resolve this by allowing the database to accept "null" values in the optional fields when reading from the `database.json` file. 

So if the employee indeed doesn't have his address filled (so it is "N/A"), then it would be recorded in the `json` as "N/A", and when it is read to be "N/A", it would be ignored, and the `Address` null object will be called instead.

Was checking it out just now, seems like we can do this by modifying the `JsonAdaptedPerson::toModelType` method. 

![image](https://user-images.githubusercontent.com/78629832/196237045-19dbe4db-677b-431b-8aca-2b6ee56cc5f3.png)
